version: "3"

volumes:
  mongodb-configdata:
  mongodb-dbdata:
  minio-config:

networks:
  func_functions:
    external: true

services:
  mongodb:
    image: "mongo:4.0-xenial"
    volumes:
     - mongodb-dbdata:/data/db
     - mongodb-configdata:/data/configdb
     - ./db-setup.sh:/docker-entrypoint-initdb.d/db-setup.sh
    networks:
     - func_functions
    env_file: env-mongodb
  minio:
    image: "minio/minio:RELEASE.2019-02-26T19-51-46Z"
    volumes:
     - /mnt/bigdata:/data
     - minio-config:/root/.minio
    networks:
     - func_functions
    env_file: env-minio
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server /data
