version: "3.5"

volumes:
  mongodb-configdata:
  mongodb-dbdata:

networks:
  func_functions:
    external: true

secrets:
  mongodb_root_username:
    file: ./secrets/mongodb_root_username.txt
    name: mongodb_root_username
  mongodb_root_password:
    file: ./secrets/mongodb_root_password.txt
    name: mongodb_root_password

services:
  mongodb:
    image: "mongo:5.0-focal"
    volumes:
      - mongodb-dbdata:/data/db
      - mongodb-configdata:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - func_functions
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_root_password
  kong:
    image: "kong:2.8.1-alpine"
    user: "kong"
    volumes:
      - ./kong-config:/opt/kong
    ports:
      - "80:8000"
      - "443:8443"
    networks:
      - func_functions
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_DECLARATIVE_CONFIG=/opt/kong/kong.yml
    deploy:
      placement:
        constraints: [node.role == manager]
