version: "3.5"

volumes:
  mongodb-configdata:
  mongodb-dbdata:
  minio-config:
  kongdb-data:

networks:
  func_functions:
    external: true

secrets:
  mongodb_root_username:
    file: ./secrets/mongodb_root_username.txt
    name: mongodb_root_username
  mongodb_root_password:
    file: ./secrets/mongodb_root_password.txt
    name: mongodb_root_password
  minio_access_key:
    file: ./secrets/minio_access_key.txt
    name: minio_access_key
  minio_secret_key:
    file: ./secrets/minio_secret_key.txt
    name: minio_secret_key
  kong_postgres_password:
    file: ./secrets/kong_postgres_password.txt
    name: kong_postgres_password

services:
  mongodb:
    image: "mongo:4.0-xenial"
    volumes:
      - mongodb-dbdata:/data/db
      - mongodb-configdata:/data/configdb
    networks:
      - func_functions
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_root_password
  minio:
    image: "minio/minio:RELEASE.2020-09-21T22-31-59Z"
    volumes:
      - ${MINIO_STORAGE_PATH:-/mnt/bigdata}:/data
      - minio-config:/root/.minio
    networks:
      - func_functions
    secrets:
      - source: minio_access_key
        target: access_key
      - source: minio_secret_key
        target: secret_key
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server /data
  kong:
    image: "kong:2.0-centos"
    ports:
      - "8000:8000"
      - "8443:8443"
    networks:
      - func_functions
    secrets:
      - kong_postgres_password
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PG_PASSWORD_FILE=/run/secrets/kong_postgres_password
    deploy:
      placement:
        constraints: [node.role == manager]
  kong-database:
    image: "postgres:11.1-alpine"
    volumes:
      - kongdb-data:/var/lib/postgresql/data
    networks:
      - func_functions
    secrets:
      - kong_postgres_password
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD_FILE=/run/secrets/kong_postgres_password
    deploy:
      placement:
        constraints: [node.role == manager]
