version: "3"

volumes:
  mongodb-configdata:
  mongodb-dbdata:
  minio-config:
  kongdb-data:

networks:
  func_functions:
    external: true

services:
  mongodb:
    image: "mongo:4.0-xenial"
    volumes:
     - mongodb-dbdata:/data/db
     - mongodb-configdata:/data/configdb
     - ./db-setup.sh:/docker-entrypoint-initdb.d/db-setup.sh
    networks:
     - func_functions
    env_file: env-mongodb
  minio:
    image: "minio/minio:RELEASE.2020-06-01T17-28-03Z"
    volumes:
     - /mnt/bigdata:/data
     - minio-config:/root/.minio
    networks:
     - func_functions
    env_file: env-minio
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server /data
  kong:
    image: "kong:2.0-centos"
    ports:
     - "8000:8000"
     - "8443:8443"
    networks:
     - func_functions
    env_file: env-kong
    environment:
     - KONG_DATABASE=postgres
     - KONG_PG_HOST=kong-database
     - KONG_PROXY_ACCESS_LOG=/dev/stdout
     - KONG_ADMIN_ACCESS_LOG=/dev/stdout
     - KONG_PROXY_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_ERROR_LOG=/dev/stderr
    deploy:
      placement:
        constraints: [node.role == manager]
  kong-database:
    image: "postgres:11.1-alpine"
    volumes:
     - kongdb-data:/var/lib/postgresql/data
    networks:
     - func_functions
    env_file: env-kong
    environment:
     - POSTGRES_USER=kong
     - POSTGRES_DB=kong
    deploy:
      placement:
        constraints: [node.role == manager]
