version: "3.5"

volumes:
  mongodb-configdata:
  mongodb-dbdata:
  minio-config:

networks:
  func_functions:
    external: true

secrets:
  mongodb_root_username:
    file: ./secrets/mongodb_root_username.txt
    name: mongodb_root_username
  mongodb_root_password:
    file: ./secrets/mongodb_root_password.txt
    name: mongodb_root_password
  minio_access_key:
    file: ./secrets/minio_access_key.txt
    name: minio_access_key
  minio_secret_key:
    file: ./secrets/minio_secret_key.txt
    name: minio_secret_key

services:
  mongodb:
    image: "mongo:6-jammy"
    volumes:
      - mongodb-dbdata:/data/db
      - mongodb-configdata:/data/configdb
    networks:
      - func_functions
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_root_password
  minio:
    image: "quay.io/minio/minio:RELEASE.2022-10-24T18-35-07Z"
    volumes:
      - ${MINIO_STORAGE_PATH:-/mnt/bigdata}:/data
      - minio-config:/root/.minio
    networks:
      - func_functions
    secrets:
      - source: minio_access_key
        target: access_key
      - source: minio_secret_key
        target: secret_key
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server /data --console-address ":9001"
  kong:
    image: "kong:2.8.1-alpine"
    user: "kong"
    volumes:
      - ./kong-config:/opt/kong
    ports:
      - "8000:8000"
      - "8443:8443"
    networks:
      - func_functions
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_DECLARATIVE_CONFIG=/opt/kong/kong.yml
    deploy:
      placement:
        constraints: [node.role == manager]
