version: "3"

volumes:
  mongodb-configdata:
  mongodb-dbdata:

networks:
  func_functions:
    external: true

services:
  mongodb:
    image: "mongo:4.0-xenial"
    volumes:
     - mongodb-dbdata:/data/db
     - mongodb-configdata:/data/configdb
     - ./db-setup.sh:/docker-entrypoint-initdb.d/db-setup.sh
    networks:
     - func_functions
    env_file: env-file
  minio:
    image: "minio/minio:RELEASE.2018-12-06T01-27-43Z"
    volumes:
     - /mnt/bigdata:/data1
    networks:
     - func_functions
    env_file: env-file
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server /data1
