version: "3"

volumes:
  mongodb-configdata:
  mongodb-dbdata:

networks:
  func_functions:
    external: true

services:
  mongodb:
    image: "mongo:4.0-xenial"
    volumes:
     - mongodb-dbdata:/data/db
     - mongodb-configdata:/data/configdb
     - ./db-setup.sh:/docker-entrypoint-initdb.d/db-setup.sh
    networks:
     - func_functions
    env_file: env-file
